version: '3'

services:
  master:
    image: chrislusf/seaweedfs # use a remote image
    restart: always
    ports:
    - 9333:9333
    - 19333:19333
    command: "master"
  volume:
    image: chrislusf/seaweedfs # use a remote image
    restart: always
    ports:
    # - 8080:8080
    - 18080:18080
    command: 'volume -max=15 -mserver="master:9333" -port=8080'
    volumes:
      - "${ENV_SEAWEEDFS_VOLUME}:/data"
    depends_on:
    - master
  filer:
    image: chrislusf/seaweedfs # use a remote image
    restart: always
    ports:
    - 8888:8888
    - 18888:18888
    command: 'filer -master="master:9333"'
    volumes:
      - "${ENV_SEAWEEDFS_FILEDB}:/data/filerdb"
    tty: true
    stdin_open: true
    depends_on:
    - master
    - volume
  s3:
    image: chrislusf/seaweedfs # use a remote image
    restart: always
    ports:
    - 8333:8333
    command: 's3 -filer="filer:8888"'
    depends_on:
    - master
    - volume
    - filer