version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.7.14-management
    container_name: rabbitmq1
    hostname: rabbitmq1
    restart: always
    network_mode: host
    environment:
      - RABBITMQ_NODENAME=rabbit
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
      - RABBITMQ_ERLANG_COOKIE="06BF898C-C43F-4A2F-9DBC-10DE353302C5"
    extra_hosts:
      - "rabbitmq1:172.17.0.14"
      - "rabbitmq2:172.17.0.13"