version: '3'
services:
  nginx:
    container_name: blog_nginx
    image: nginx:latest
    # 端口映射
    ports:
      - 80:80
    # 数据卷
    volumes:
      - "$PWD/django/nginx/conf.d:/etc/nginx/conf.d"
      - "$PWD/django/www:/data/django/www"
    links:
      - django:blog_django

  django:
    container_name: blog_django
    build: .
    #image指定build Dockerfile生成的镜像的名称
    image: debian_py36:1.1
    ports:
      - 8088:8088
    volumes:
      - "$PWD:/data/"
    #command: uwsgi --ini /data/django/www/mblog/uwsgi.ini
    
