version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    # 环境变量
    environment:
      # mysql密码
      - MYSQL_ROOT_PASSWORD=molotest123
    # 数据库数据持久化
    volumes:
      - "/Users/xliang/Documents/workspace/mysql/data:/var/lib/mysql"
      - "/Users/xliang/Documents/workspace/mysql/conf:/etc/mysql/mysql.conf.d"
      - "/Users/xliang/Documents/workspace/mysql/logs:/logs"
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=test
      - RABBITMQ_DEFAULT_PASS=test
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  trace:
    image: jaegertracing/jaeger-agent:1.9
    restart: always
    ports:
      - "5775:5775"
      - "6831:6831"
      - "6832:6832"
      - "5778:5778"