version: '3'
services:
  nginx:
    container_name: nginx_flask
    image: nginx:latest
    # 端口映射
    ports:
      - 80:80
    # 磁盘映射
    volumes:
      - "$PWD/flask/nginx/conf.d:/etc/nginx/conf.d"
      - "$PWD/flask/www:/data/flask/www"
    links:
      - flask:myflask
      
  flask:
    container_name: myflask
    build: .
    image: env_py36:1.1
    ports:
      - 8089:8089
    volumes:
      - "$PWD:/data/"
    # 环境变量
    environment:
      - MAIL_USERNAME=${ENV_MAIL_USERNAME}
      - MAIL_PASSWORD=${ENV_MAIL_PASSWORD}
      - FLASKY_ADMIN=${ENV_MAIL_ADMIN}
      - SECRET_KEY=${ENV_SECRET_KEY}