version: '3'
services:
  nginx:
    container_name: nginx_flask
    image: nginx:latest
    # 端口映射
    ports:
      - 80:80
    # 磁盘映射
    volumes:
      - "$PWD/flask/nginx/conf.d:/etc/nginx/conf.d"
      - "$PWD/flask/www:/data/flask/www"
    links:
      - flask:myflask
      
  flask:
    container_name: myflask
    build: .
    image: debian_py36:1.3
    ports:
      - 8089:8089
    volumes:
      - "$PWD:/data/"