version: '3'
services:
  redis:
      image: "redis:alpine"
      container_name: redis_1
      restart: always
      command: redis-server --requirepass molotest123
      ports:
        - "6379:6379"